### ISSUE TITLE
Task3 issues

### ISSUE THREAD

**Issue by Dlegend7** [yuanqing811/ISIC2018#10]
@yuanqing811 Thanks for your code!
There are some issues when running your code:
1- When running  cls_train.py, it uses only 32 instances, and there are no instances for some catagories such as DF or VASC as in the screenshots. In the evaluation phase, the results are not as good as what you have stated. Here I have attached the results I get when running cls_eval.py 
Could you please suggest the soulution to this issue?
 
![screenshot from 2018-07-05 10-27-50](https://user-images.githubusercontent.com/38858
![screenshot from 2018-07-05 11-04-25](https://user-images.githubusercontent.com/38858584/42331343-33548536-8043-11e8-9cec-4dd7e9c30074.png)
584/42329213-280252e4-803e-11e8-82db-1e7b01c73f3d.png)

**Comment by yuanqing811** [comment]
Please set debug_visualize flag to False on line 46 of cls_train.py
