### ISSUE TITLE
ModuleNotFoundError: No module named 'datasets.ISIC2018'

### ISSUE THREAD

**Issue by fera0013** [yuanqing811/ISIC2018#4]
I am trying to follow your instructions, but when I run

`C:\Users\me\GitHub\ISIC2018Challenge>python runs/cls_train.py`

I get 

```
Traceback (most recent call last):
  File "runs/cls_train.py", line 4, in <module>
    from datasets.ISIC2018 import *
ModuleNotFoundError: No module named 'datasets.ISIC2018'
```

The folder /datasets/ISIC2018 subfolder is there, but apparently the import statement in cls_train.py misinterprets the folder as a module. 

Did I miss a step in the setup?

**Comment by tavildar** [comment]
Hi, your base project directory needs to be in the PYTHONPATH. 

> export PYTHONPATH="${PYTHONPATH}:yourprojectpath"

**Comment by fera0013** [comment]
What path do I have to add exactly? 

I tried `export PYTHONPATH="${PYTHONPATH}:c:/ISIC2018"` and `export PYTHONPATH="${PYTHONPATH}:c:/ISIC2018/datasets/ISIC2018"`

but that didn't fix anything.

**Comment by cvvaldez** [comment]
Hey @fera0013 how did you resolved the issue? I am facing the same even when running the below command from my Windows Powershell:
`set PYTHONPATH="${PYTHONPATH}:\Users\omarv\Anaconda3\pkgs\python-3.7.3-h8c8aaf0_0\Scripts\ISIC2018"`

I am getting the below exception, mostly in all scripts:
```File "preprocess_data.py", line 3, in <module>
    from datasets.ISIC2018 import load_training_data, load_validation_data, load_test_data
ModuleNotFoundError: No module named 'datasets'
```
