### ISSUE TITLE
Change request: Provide an evaluation setup for development

### ISSUE THREAD

**Issue by fera0013** [yuanqing811/ISIC2018#8]
For development, it would be really convenient to have a setup running on only a few samples, to get a quicker feedback. I have already tried and removed the majority of the images and the corresponding rows in the csv for Task 3.  But then I ran into 

```
_init__.py", line 232, in partition_task3_data
    y_valid = y[valid_indices]
IndexError: boolean index did not match indexed array along dimension 0; dimension is 10015 but corresponding boolean dimension is 59
```

**Comment by tavildar** [comment]
Hi, the simplest thing we do is use the "debug_visualize" flag in the cls_train file. This will only use 32 samples from the training and validation sets.  You can turn off the the call to BatchVisualization within the debug_visualize condition in case you just want to run without visualizing.

**Comment by fera0013** [comment]
Awesome! Thanks.
